# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsn <- function(r, xi, omega, alpha) {
    .Call(`_SkewNormalMix_dsn`, r, xi, omega, alpha)
}

rcpp_hello_world <- function() {
    .Call(`_SkewNormalMix_rcpp_hello_world`)
}

